// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW82tKBCBQFYE-xBGo9NQe7qsiEmQr69o',
    appId: '1:717064584157:web:6d3a0ef33a28220a5dd434',
    messagingSenderId: '717064584157',
    projectId: 'fooddeliveryapp-ca9f5',
    authDomain: 'fooddeliveryapp-ca9f5.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-ca9f5.firebasestorage.app',
    measurementId: 'G-0Z74BM7QVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLlrhAVFsj9uGOtpz6eUPW9bziWYAJXcc',
    appId: '1:717064584157:android:0137ce09b193fd4d5dd434',
    messagingSenderId: '717064584157',
    projectId: 'fooddeliveryapp-ca9f5',
    storageBucket: 'fooddeliveryapp-ca9f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAPnnR34xJq6SNepmXNcowCcgU3S1ou4w',
    appId: '1:717064584157:ios:e2b7333bda409d4e5dd434',
    messagingSenderId: '717064584157',
    projectId: 'fooddeliveryapp-ca9f5',
    storageBucket: 'fooddeliveryapp-ca9f5.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAPnnR34xJq6SNepmXNcowCcgU3S1ou4w',
    appId: '1:717064584157:ios:e2b7333bda409d4e5dd434',
    messagingSenderId: '717064584157',
    projectId: 'fooddeliveryapp-ca9f5',
    storageBucket: 'fooddeliveryapp-ca9f5.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW82tKBCBQFYE-xBGo9NQe7qsiEmQr69o',
    appId: '1:717064584157:web:6aceba13b57a47eb5dd434',
    messagingSenderId: '717064584157',
    projectId: 'fooddeliveryapp-ca9f5',
    authDomain: 'fooddeliveryapp-ca9f5.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-ca9f5.firebasestorage.app',
    measurementId: 'G-R0ZD7C239Z',
  );
}
